media:
  input: assets/images
  output: /assets/images
  extensions: [png, jpg, jpeg, webp, svg] 
content:
  - name: navigation
    label: Nawigacja
    type: collection
    path: '_data/navigation.yml'
    fields:
      - name: text
        label: Tekst
        type: string
      - name: url
        label: URL
        type: string
      - name: menu_type
        label: Typ menu
        type: string
  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: timzone
        label: Strefa czasowa
        type: string
      - name: url
        label: Strona główna
        type: string