media:
  input: assets/images
  output: /assets/images
  extensions: [png, jpg, jpeg, webp, svg] 
content:
  - name: members
    type: collection
    label: Autorzy
	path: _data/team_carousel.yml
	format: yaml
	fields:
	  - name: name
		label: Imię i nazwisko
		type: text
	  - name: designation
		label: Stanowisko
		type: text
	  - name: description
		label: Opis
		type: textarea
	  - name: image
		label: Zdjęcie
		type: image
		directory: assets/images/authors