media:
  input: assets/images
  output: /assets/images
  extensions: [png, jpg, jpeg, webp, svg] 
content:
  - name: navigation
    label: Nawigacja
    type: collection
    path: _data/navigation.yml
    format: text
    fields:
      main_menu:
        type: list
        label: Menu główne
        fields:
          - name: text
            label: Tekst
            type: text
          - name: url
            label: URL
            type: text
          - name: menu_type
            label: Typ menu
            type: select
            options: ["simple", "dropdown", "mega"]